// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: CarDial

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_ArcSpeed = NULL;lv_obj_t *ui_ArcRPM1 = NULL;lv_obj_t *ui_LabelSpeed = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_LabelRPM = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_ArcGas = NULL;lv_obj_t *ui_ArcTemp = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_LabelBattery = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_Image6 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ArcSpeed = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ArcSpeed, 245);
lv_obj_set_height( ui_ArcSpeed, 245);
lv_obj_set_align( ui_ArcSpeed, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ArcSpeed, 0,700);
lv_arc_set_value(ui_ArcSpeed, 200);
lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcSpeed, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcSpeed, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcSpeed, lv_color_hex(0xD86300), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcSpeed, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcSpeed, 15, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcSpeed, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcSpeed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcSpeed, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ArcRPM1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ArcRPM1, 205);
lv_obj_set_height( ui_ArcRPM1, 205);
lv_obj_set_align( ui_ArcRPM1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ArcRPM1, 0,700);
lv_arc_set_value(ui_ArcRPM1, 200);
lv_obj_set_style_arc_color(ui_ArcRPM1, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcRPM1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcRPM1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcRPM1, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_ArcRPM1, lv_color_hex(0x6E74ED), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcRPM1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_ArcRPM1, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcRPM1, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcRPM1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcRPM1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelSpeed = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSpeed, 0 );
lv_obj_set_y( ui_LabelSpeed, -3 );
lv_obj_set_align( ui_LabelSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSpeed,"35");
lv_obj_set_style_text_font(ui_LabelSpeed, &ui_font_Fever64, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, 37 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"MPH");

ui_LabelRPM = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelRPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelRPM, 0 );
lv_obj_set_y( ui_LabelRPM, -48 );
lv_obj_set_align( ui_LabelRPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelRPM,"1200");

ui_Image1 = lv_image_create(ui_Screen1);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 120
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 120
lv_obj_set_x( ui_Image1, -30 );
lv_obj_set_y( ui_Image1, 81 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image1,8);

ui_ArcGas = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ArcGas, 50);
lv_obj_set_height( ui_ArcGas, 50);
lv_obj_set_x( ui_ArcGas, -30 );
lv_obj_set_y( ui_ArcGas, 81 );
lv_obj_set_align( ui_ArcGas, LV_ALIGN_CENTER );
lv_arc_set_value(ui_ArcGas, 50);
lv_obj_set_style_arc_width(ui_ArcGas, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcGas, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_ArcGas, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcGas, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcGas, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcGas, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ArcTemp = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_ArcTemp, 50);
lv_obj_set_height( ui_ArcTemp, 50);
lv_obj_set_x( ui_ArcTemp, 30 );
lv_obj_set_y( ui_ArcTemp, 82 );
lv_obj_set_align( ui_ArcTemp, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ArcTemp, 40,130);
lv_arc_set_value(ui_ArcTemp, 50);
lv_arc_set_rotation(ui_ArcTemp,4);
lv_obj_set_style_arc_width(ui_ArcTemp, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcTemp, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_ArcTemp, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_ArcTemp, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcTemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcTemp, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Image3 = lv_image_create(ui_Screen1);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 640
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 640
lv_obj_set_x( ui_Image3, 56 );
lv_obj_set_y( ui_Image3, 16 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image3,8);

ui_LabelBattery = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelBattery, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBattery, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelBattery, 56 );
lv_obj_set_y( ui_LabelBattery, 31 );
lv_obj_set_align( ui_LabelBattery, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBattery,"14.1V");
lv_obj_set_style_text_font(ui_LabelBattery, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Image4, &ui_img_1105797868);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 320
lv_obj_set_x( ui_Image4, 30 );
lv_obj_set_y( ui_Image4, 80 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image4,18);

ui_Image5 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Image5, &ui_img_307720245);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 320
lv_obj_set_x( ui_Image5, -29 );
lv_obj_set_y( ui_Image5, 80 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image5,18);

ui_Image6 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Image6, &ui_img_802384555);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 320
lv_obj_set_x( ui_Image6, 56 );
lv_obj_set_y( ui_Image6, 15 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image6,18);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_ArcSpeed= NULL;
ui_ArcRPM1= NULL;
ui_LabelSpeed= NULL;
ui_Label2= NULL;
ui_LabelRPM= NULL;
ui_Image1= NULL;
ui_ArcGas= NULL;
ui_ArcTemp= NULL;
ui_Image3= NULL;
ui_LabelBattery= NULL;
ui_Image4= NULL;
ui_Image5= NULL;
ui_Image6= NULL;

}
