// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: CarDial

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_ArcSpeed;
extern lv_obj_t *ui_ArcRPM1;
extern lv_obj_t *ui_LabelSpeed;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_LabelRPM;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_ArcGas;
extern lv_obj_t *ui_ArcTemp;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_LabelBattery;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

