// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_Clock;
extern lv_obj_t *ui_LabelTime;
extern lv_obj_t *ui_LabelDate;
extern lv_obj_t *ui_Two;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Three;
extern lv_obj_t *ui_Roller1;
extern lv_obj_t *ui_LabelOption;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

