// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen3 = NULL;lv_obj_t *ui_TabView1 = NULL;lv_obj_t *ui_Clock = NULL;lv_obj_t *ui_LabelTime = NULL;lv_obj_t *ui_LabelDate = NULL;lv_obj_t *ui_Two = NULL;lv_obj_t *ui_TextArea1 = NULL;lv_obj_t *ui_Three = NULL;lv_obj_t *ui_Roller1 = NULL;lv_obj_t *ui_LabelOption = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_Screen3);
lv_tabview_set_tab_bar_size(ui_TabView1,30);
lv_obj_set_width( ui_TabView1, 320);
lv_obj_set_height( ui_TabView1, 170);
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_TabView1), &lv_font_montserrat_12,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Clock = lv_tabview_add_tab(ui_TabView1, "Clock");

ui_LabelTime = lv_label_create(ui_Clock);
lv_obj_set_width( ui_LabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTime, 0 );
lv_obj_set_y( ui_LabelTime, 24 );
lv_obj_set_align( ui_LabelTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTime,"Fri Aug 1");
lv_obj_set_style_text_font(ui_LabelTime, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelDate = lv_label_create(ui_Clock);
lv_obj_set_width( ui_LabelDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDate, 0 );
lv_obj_set_y( ui_LabelDate, -18 );
lv_obj_set_align( ui_LabelDate, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDate,"9:20:21");
lv_obj_set_style_text_font(ui_LabelDate, &ui_font_SavateBold56, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Two = lv_tabview_add_tab(ui_TabView1, "Two");

ui_TextArea1 = lv_textarea_create(ui_Two);
lv_obj_set_width( ui_TextArea1, 150);
lv_obj_set_height( ui_TextArea1, 70);
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea1,"hello");
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");

ui_Three = lv_tabview_add_tab(ui_TabView1, "Three");

ui_Roller1 = lv_roller_create(ui_Three);
lv_roller_set_options( ui_Roller1, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller1, 100);
lv_obj_set_width( ui_Roller1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller1, 103 );
lv_obj_set_y( ui_Roller1, -6 );
lv_obj_set_align( ui_Roller1, LV_ALIGN_CENTER );

ui_LabelOption = lv_label_create(ui_Three);
lv_obj_set_width( ui_LabelOption, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOption, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelOption, -50 );
lv_obj_set_y( ui_LabelOption, 1 );
lv_obj_set_align( ui_LabelOption, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelOption,"Option 1");
lv_obj_set_style_text_font(ui_LabelOption, &ui_font_SavateBold40, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
ui_TabView1= NULL;
ui_Clock= NULL;
ui_LabelTime= NULL;
ui_LabelDate= NULL;
ui_Two= NULL;
ui_TextArea1= NULL;
ui_Three= NULL;
ui_Roller1= NULL;
ui_LabelOption= NULL;

}
