// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_LabelHeap = NULL;lv_obj_t *ui_LabelPSRAM = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -105 );
lv_obj_set_y( ui_Label5, -48 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Free Heap");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -97 );
lv_obj_set_y( ui_Label1, 24 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Free PSRAM");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHeap = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_LabelHeap, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHeap, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHeap, 45 );
lv_obj_set_y( ui_LabelHeap, -51 );
lv_obj_set_align( ui_LabelHeap, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHeap,"133.24 KB");
lv_obj_set_style_text_font(ui_LabelHeap, &ui_font_SavateBold40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPSRAM = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_LabelPSRAM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPSRAM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPSRAM, 45 );
lv_obj_set_y( ui_LabelPSRAM, 21 );
lv_obj_set_align( ui_LabelPSRAM, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPSRAM,"0 B");
lv_obj_set_style_text_font(ui_LabelPSRAM, &ui_font_SavateBold40, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Label5= NULL;
ui_Label1= NULL;
ui_LabelHeap= NULL;
ui_LabelPSRAM= NULL;

}
